<?php
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$targetProperties = ['dcndl:callNumber',
    'archiveshub:dateCreatedAccumulatedString',
    'archiveshub:level',
    'dcterms:extent',
    'dcterms:creator',
    'archiveshub:hasBiographicalHistory',
    'archiveshub:custodialHistory',
    'archiveshub:acquisitions',
    'archiveshub:scopecontent',
    'archiveshub:appraisal',
    'archiveshub:accruals',
    'archiveshub:accessRestrictions',
    'archiveshub:useRestrictions',
    'dcterms:language',
    'archiveshub:physicalTechnicalRequirements',
    'archiveshub:otherFindingAids',
    'archiveshub:locationOfOriginals',
    'archiveshub:alternateFormsAvailable',
    'archiveshub:relatedMaterial',
    'archiveshub:bibliography',
    'archiveshub:location',
];
?>
<?php foreach ($targetProperties as $targetProperty): ?>
    <?php if (isset($values[$targetProperty])):?>
        <?php foreach ($values[$targetProperty]['values'] as $value): ?>
        <tr class="property">
            <th>
                <label>
                <?php if ($values[$targetProperty]['alternate_label']): ?>
                <?php echo $escape($values[$targetProperty]['alternate_label']); ?>
                <?php else: ?>
                <?php echo $escape($this->translate($values[$targetProperty]['property']->label())); ?>
                <?php endif; ?>
                <?php if ('term' === $labelInfo): ?>
                <span class="field-term">(<?php echo $escape($values[$targetProperty]['property']->term()); ?>)</span>
                <?php elseif ('vocab' === $labelInfo): ?>
                <span class="field-term">(<?php echo $escape($values[$targetProperty]['property']->vocabulary()->label()); ?>)</span>
                <?php endif; ?>
                </label>
            </th>
            <td>
                <?php
                $class = 'value';
                if ('resource' == $value->type()) {
                } elseif ('uri' == $value->type()) {
                    $class .= ' uri';
                }
                ?>
                    <div class="<?php echo $class; ?>" lang="<?php echo $escape($value->lang()); ?>">
                    <?php if ($language = $value->lang()): ?>
                    <span class="language"><?php echo $language; ?></span>
                    <?php endif; ?>
                    <?php if (strcmp('resource', $value->type()) != 0): ?>
                    <?php echo $value->asHtml(); ?>
                    <?php endif;?>
                </div>
              </td>
        </tr>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach;?>
