<?php
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$targetProperties = ['archiveshub:dateCreatedAccumulatedString',
    'dcndl:callNumber',
    'archiveshub:level',
    'utarchives:resourceCategory',
    'dcterms:extent',
    'dcterms:creator',
    'dcterm:description',
    'archiveshub:hasBiographicalHistory',
    'archiveshub:custodialHistory',
    'archiveshub:acquisitions',
    'archiveshub:scopecontent',
    'utarchives:notes',
    'archiveshub:appraisal',
    'archiveshub:accruals',
    'archiveshub:accessRestrictions',
    'archiveshub:useRestrictions',
    'dcterms:language',
    'archiveshub:physicalTechnicalRequirements',
    'archiveshub:otherFindingAids',
    'utarchives:specialPage',
    'archiveshub:locationOfOriginals',
    'archiveshub:alternateFormsAvailable',
    'archiveshub:relatedMaterial',
    'archiveshub:separatedMaterial',
    'archiveshub:bibliography',
    'archiveshub:location',
    'dcterms:rights',
    'utarchives:metadataRights',
];
?>
<?php foreach ($targetProperties as $targetProperty): ?>
    <?php if (isset($values[$targetProperty])):?>
        <?php foreach ($values[$targetProperty]['values'] as $value): ?>
        <tr class="property">
            <th>
                <label>
                <?php if ($values[$targetProperty]['alternate_label']): ?>
                <?php echo $escape($values[$targetProperty]['alternate_label']); ?>
                <?php else: ?>
                <?php echo $escape($this->translate($values[$targetProperty]['property']->label())); ?>
                <?php endif; ?>
                <?php if ('term' === $labelInfo): ?>
                <span class="field-term">(<?php echo $escape($values[$targetProperty]['property']->term()); ?>)</span>
                <?php elseif ('vocab' === $labelInfo): ?>
                <span class="field-term">(<?php echo $escape($values[$targetProperty]['property']->vocabulary()->label()); ?>)</span>
                <?php endif; ?>
                </label>
            </th>
            <td>
                <?php
                $class = 'value';
                if ('resource' == $value->type()) {
                } elseif ('uri' == $value->type()) {
                    $class .= ' uri';
                }
                ?>
                    <div class="<?php echo $class; ?>" lang="<?php echo $escape($value->lang()); ?>">
                        <?php if($targetProperty == "dcterms:rights" || $targetProperty == "utarchives:metadataRights"): ?>
                            <?php if($value->uri() == "http://creativecommons.org/licenses/by/4.0/"){
                                echo '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.';
                            } else if($value->uri() == "http://creativecommons.org/licenses/by-sa/4.0/"){
                                echo '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.';
                            } else if($value->uri() == "http://creativecommons.org/licenses/by-nc/4.0/"){
                                echo '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.';
                            } else if($value->uri() == "http://creativecommons.org/licenses/by-nc-sa/4.0/"){
                                echo '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.';
                            } else if($value->uri() == "http://creativecommons.org/publicdomain/mark/1.0/"){
                                echo '<a href="http://creativecommons.org/publicdomain/mark/1.0/"><img src="https://licensebuttons.net/p/mark/1.0/88x31.png" /></a>';
                            } else if($value->uri() == "http://creativecommons.org/publicdomain/zero/1.0/"){
                                echo '<a href="http://creativecommons.org/publicdomain/zero/1.0/"><img src="https://licensebuttons.net/p/zero/1.0/88x31.png" /></a>';
                            } else {
                                echo $value->asHtml();
                            } ?>
                        <?php else: ?>
                            <?php if ($language = $value->lang()): ?>
                                <span class="language"><?php echo $language; ?></span>
                            <?php endif; ?>
                            <?php if (strcmp('resource', $value->type()) != 0): ?>
                                <?php echo $value->asHtml(); ?>
                            <?php endif;?>
                        <?php endif;?>
                    </div>
              </td>
        </tr>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach;?>
