<?php
function isSearchPage() {
    if (strpos($_SERVER['REQUEST_URI'], 'docarchive?search=')) {
        return true;
    }
    if (strpos($_SERVER['REQUEST_URI'], 'search-children?search=')) {
        return true;
    }
    return false;
}
$userBar = $this->userBar();
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
if ($userBar) {
    $this->headLink()->prependStylesheet($this->assetUrl('css/style-login.css?') . date('YmdHis'));
} else {
    $this->headLink()->prependStylesheet($this->assetUrl('css/style.css') . date('YmdHis'));
}

$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap.min.css'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-tree.css'));
// $this->headLink()->appendStylesheet($this->assetUrl('css/fa-regular.css'));
// $this->headLink()->appendStylesheet($this->assetUrl('css/fontawesome.min.css'));
$this->headLink()->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/themes/docarchive/asset/img/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND');
$this->headScript()->prependFile($this->assetUrl('js/docarchive.js'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$navigation = $this->docarchiveNavigation($site);
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
$title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
// セッションでキャッシュエスケープ用のコードを表示制御する
if (!$_SESSION) {
    $_SESSION['cache'] = 0;
} else {
    if (!isset($_SESSION['cache'])) {
        $_SESSION['cache'] = 0;
    } else if ($_SESSION['cache'] < 2) {
        $_SESSION['cache'] = $_SESSION['cache'] + 1;
    } else {
        $_SESSION['cache'] = 0;
    }
}
$isHomePage = 0;
$top_image = $this->themeSettingAssetUrl('top_image');
try {
    //Nextモジュールが有効でない場合
    $isHomePage = $this->isHomePage();
} catch (Exception $e) {
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/imagesloaded@4.1.4/imagesloaded.pkgd.min.js"></script>
    <?php $this->headScript()->prependFile($this->assetUrl('js/bootstrap.min.js')); ?>
    <script>
        $(function() {
            $( document ).tooltip();
        });
        function startSearch() {
            $('#loading').show();
        }
    </script>
    <style>
      label {
        display: inline-block;
        width: 5em;
      }
    </style>
    <style>
        @-webkit-keyframes loading {
        from {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg); }
        to {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg); } }
        @keyframes loading {
        from {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg); }
        to {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg); } }
        /* ローディング画面の背景部分 */
        #loading {
            width: 100vw;
            height: 100vh;
            background-color: #f6f7f8;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 100; }

        /* ローディング回転部分 */
        #loading-main:after, #loading-main:before {
            content: "検索中";
            display: block;
            width: 100%;
            height: 100%;
            margin-left: -1.5%;
            position: absolute;
            top: 40%;
            left: 50%;
            border-radius: 110%; }

        /* #loading-main {
            display: block;
            width: 30px;
            height: 30px;
            position: absolute;
            top: 45%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 105; } */
        /* #loading-main:after {
            -webkit-animation: loading 0.75s linear infinite;
            animation: loading 0.75s linear infinite;
            border: 1px solid transparent;
            border-top-color: #666; }
        #loading-main:before {
            border: 1px solid rgba(51, 51, 51, 0.15); } */
    </style>
    <?php if (!isset($_SESSION['cache']) || $_SESSION['cache'] <= 1): ?>
        <meta http-equiv="Pragma" content="no-cache">
    <?php endif; ?>
    <?php if (!isset($_SESSION['cache'])  || $_SESSION['cache'] == 0 || $_SESSION['cache'] == 2): ?>
    <meta http-equiv="Cache-Control" content="no-cache">
    <?php endif; ?>
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <?php if (isSearchPage()): // 検索ページ ?>
            <!-- <script>
                imagesLoaded( '.l-main', { background: ".demo-kv" }, function() {
                    const msM = 1000;
                    loading.style.transition = 'opacity ' + msM + 'ms';

                    const loadingOpacity = function(){
                        loading.style.opacity = 0;
                    }
                    const loadingDisplay = function(){
                        loading.style.display = "none";
                    }

                    setTimeout(loadingOpacity, 1000);
                    setTimeout(loadingDisplay, 1000 + msM);
                });
            </script> -->


        <?php endif; ?>
        <div id="loading" style="display: none">
            <div id="loading-main"></div>
        </div>

        <header<?php if ($userBar) { echo ' style="padding-top:0;"';} ?>>
        <?php echo $userBar; ?>
        <div class="header-content">
            <?php if ($this->themeSetting('logo')): ?>
             <a href="<?php echo $site->url(); ?>" class="site-title">
                <h1><?php echo $title; ?><span class="title"><?php echo $site->title(); ?></span>
                </h1></a>
            <?php else: ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
            <?php endif; ?>
            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </div>
        </header>
        <?php if ($isHomePage && $top_image): ?>
        <style>
            @media screen and (max-width: 1010px) {
                .boxbackground {
                    position: relative;
                    top: 140px!important;
                    width: 100%;
                    background: url("<?php echo $top_image; ?>") no-repeat center center;
                    background-size: cover;
                }
            }
            @media screen and (max-width: 799px) {
                .boxbackground {
                    position: relative;
                    top: 90px!important;
                    width: 100%;
                    background: url("<?php echo $top_image; ?>") no-repeat center center;
                    background-size: cover;
                }
            }
            @media screen and (max-width: 630px) {
                .boxbackground {
                    position: relative;
                    top: 115px!important;
                    width: 100%;
                    background: url("<?php echo $top_image; ?>") no-repeat center center;
                    background-size: cover;
                }
            }
            @media screen and (max-width: 460px) {
                .boxbackground {
                    position: relative;
                    top:135px;
                    width: 100%;
                    background: url("<?php echo $top_image; ?>") no-repeat center center;
                    background-size: cover;
                 }
            }
            .boxbackground {
                    position: relative;
                    top:90px;
                    width: 100%;
                    background: url("<?php echo $top_image; ?>") no-repeat center center;
                    background-size: cover;
            }


        </style>

        <div class="boxbackground">
        <div style="background: rgba(0, 0, 0, 0.5);">
            <div class="container">

            <div class="row py-5 text-white text-center">
                <div class="col-xl-9 mx-auto my-5">

                <?php if ($site_sub_title = $this->themeSetting('site_sub_title')): ?>
                <h4 class="mb-3">
                    <?php echo $site_sub_title; ?>
                </h4>
                <?php endif; ?>

                <h1>
                    <?php echo $title; ?>
                </h1>
                <?php if ($site_summary = $site->summary()): ?>
                <p class="mt-3">
                    <?php echo $site_summary; ?>
                </p>
                <?php endif; ?>

                <?php if ($top_url = $this->themeSetting('top_url')): ?>
                <a href="<?php echo $top_url; ?>"
                    class="mt-3 btn btn-danger px-3" style="border-radius: 40px;">
                    <i class="fa-solid fa-magnifying-glass"></i> <?php echo $this->translate('Browse'); ?>
                </a>
                <?php endif; ?>
                </div>
            </div>

            </div>
        </div>
        </div>
        <?php endif; ?>
        <div id="content-main" role="main"<?php if ($userBar) { echo ' style="top:120px"';} ?>>
            <?php echo $this->content; ?>

        </div>
        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>
